### ISSUE TITLE
Errors and warnings while installing and running

### ISSUE THREAD

**Issue by Kukulkano** [somiibo/soundcloud-play-generator-bot#1]
Hi. Being on Xubuntu 18.04 (x86_64), the following errors appear during install:

```
gyp: Undefined variable napi_build_version in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-213-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/volker/soundcloud-play-generator-bot/node_modules/registry-js
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

Later on, trying npm start, it does downloading forever:

```
$ npm start

> somiibo-downloader@1.0.0 start /home/volker/soundcloud-play-generator-bot
> node src/index.js

(node:9847) UnhandledPromiseRejectionWarning: TypeError: fs.rmSync is not a function
    at Object.removeSync [as sync] (/home/volker/soundcloud-play-generator-bot/node_modules/fs-jetpack/lib/remove.js:16:6)
    at Object.remove (/home/volker/soundcloud-play-generator-bot/node_modules/fs-jetpack/lib/jetpack.js:199:14)
    at Module.module.exports (/home/volker/soundcloud-play-generator-bot/src/index.js:20:6)
    at Object.<anonymous> (/home/volker/soundcloud-play-generator-bot/src/index.js:50:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
(node:9847) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9847) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[09:59:45] Still downloading, please be patient! :)
[09:59:48] Still downloading, please be patient! :)
[09:59:51] Still downloading, please be patient! :)
[09:59:54] Still downloading, please be patient! :)
[09:59:57] Still downloading, please be patient! :)
[10:00:00] Still downloading, please be patient! :)
[10:00:03] Still downloading, please be patient! :)
[10:00:06] Still downloading, please be patient! :)
[10:00:09] Still downloading, please be patient! :)
[10:00:12] Still downloading, please be patient! :)
[10:00:15] Still downloading, please be patient! :)
[10:00:18] Still downloading, please be patient! :)
```
... continue for hours...

npm version: 3.5.2

**Comment by Kukulkano** [comment]
Same problems after system upgrade to Ubuntu 20.04 with node 10.19.0 and npm version 6.14.4.

**Comment by CodeByAidan** [comment]
Doesn't look trustworthy to me, when all the script is doing is installing some application without explicitly saying it in the README?

**Comment by Kukulkano** [comment]
Yeah. Also looks dead to me...
